# Web Server Port (Setting to 8080)
server.port=8080

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=query_executor
spring.datasource.password=sandbox_pass_123
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection Pool Limits (Crucial for preventing server crashes from too many queries)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=3000